"""Generate the packaged manual from editable UTF-8 JSON and live item scripts.

Run after editing terminal_guide.json; never hand-edit the generated Lua file.
Every live GodSystem item is included, including hidden/retired internal items.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MEDIA = ROOT / 'Contents/mods/GodSystem/42/media'
SOURCE = Path(__file__).with_name('terminal_guide.json')

def lua(value):
    if isinstance(value, str):
        return '"' + ''.join(chr(b) if 32 <= b < 127 and chr(b) not in '\\"' else '\\%03d' % b for b in value.encode('utf-8')) + '"'
    if isinstance(value, list):
        return '{' + ',\n'.join(lua(v) for v in value) + '}'
    if isinstance(value, dict):
        return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'
    raise TypeError(type(value))

def build():
    source = json.loads(SOURCE.read_text(encoding='utf-8'))
    translations = {}
    for line in (ROOT / 'tools/localization/godsystem_v11645_localization.yml').read_text(encoding='utf-8-sig').splitlines():
        if ': ' in line and not line.startswith('#'):
            k, v = line.split(': ', 1)
            translations[k] = json.loads(v)
    articles = source['articles'][:]
    ids = set()
    for a in articles:
        assert a['id'] not in ids and a['title'] and a['body'], a
        ids.add(a['id'])
    items = re.findall(r'\bitem\s+(\w+)\s*\{([^}]+)\}', (MEDIA / 'scripts/GodSystem_Items.txt').read_text(encoding='utf-8-sig'))
    for name, block in items:
        full_type = 'GodSystem.' + name
        note = source['itemNotes'].get(name, '')
        tip = translations.get('Tooltip_GodSystem_' + name, '').replace('%%', '%')
        assert tip or note, 'Missing item documentation: ' + name
        articles.append({'id': 'item.' + name, 'group': '物品图鉴', 'title': translations.get('ItemName_' + full_type, name),
                         'topic': 'items', 'fullType': full_type, 'body': '\n\n'.join(x for x in [tip, note] if x)})
    output = '-- Generated by tools/ui/generate_terminal_guide.py. Edit terminal_guide.json.\nGodSystemTerminalGuideData = ' + lua(articles) + '\nreturn GodSystemTerminalGuideData\n'
    (MEDIA / 'lua/shared/GodSystem_TerminalGuideData.lua').write_text(output, encoding='ascii')
    print(f'Guide generated: {len(articles)} articles, {len(items)} / {len(items)} live items')

if __name__ == '__main__':
    build()
