GodSystemProtocol422012 = GodSystemProtocol422012 or {}

local Protocol = GodSystemProtocol422012

Protocol.Version = "42.20.1.2"
Protocol.Module = "GodSystem_CN_422012"
Protocol.C2S = {
    Hello = "hello",
    Request = "request",
}
Protocol.S2C = {
    Hello = "hello",
    Response = "response",
    Snapshot = "snapshot",
}

Protocol.Routes = {
    ["diagnostics.snapshot"] = {
        moduleId = "runtime.diagnostics",
        method = "snapshot",
        runtime = true,
    },
    ["system.initialize"] = { moduleId = "feature.system", method = "ensureInitialized" },
    ["system.snapshot"] = { moduleId = "feature.system", method = "snapshot" },
    ["system.preference"] = { moduleId = "feature.system", method = "setPreference" },
    ["system.history"] = { moduleId = "feature.system", method = "history" },
    ["wallet.balance"] = { moduleId = "feature.wallet", method = "requestBalance" },
    ["wallet.transfer"] = { moduleId = "feature.wallet", method = "requestTransfer" },
    ["wallet.consolidate"] = { moduleId = "feature.wallet", method = "requestConsolidate" },
    ["bank.summary"] = { moduleId = "feature.bank", method = "requestSummary" },
    ["bank.execute"] = { moduleId = "feature.bank", method = "execute" },
    ["tasks.generate"] = { moduleId = "feature.tasks", method = "generate" },
    ["tasks.refresh"] = { moduleId = "feature.tasks", method = "refresh" },
    ["tasks.snapshot"] = { moduleId = "feature.tasks", method = "snapshot" },
    ["tasks.autoClaim"] = { moduleId = "feature.tasks", method = "setAutoClaim" },
    ["tasks.accept"] = { moduleId = "feature.tasks", method = "accept" },
    ["tasks.progress"] = { moduleId = "feature.tasks", method = "progress" },
    ["tasks.claim"] = { moduleId = "feature.tasks", method = "claim" },
    ["tasks.fail"] = { moduleId = "feature.tasks", method = "fail" },
    ["shop.catalog"] = { moduleId = "feature.shop", method = "catalog" },
    ["shop.list"] = { moduleId = "feature.shop", method = "listItem" },
    ["shop.hide"] = { moduleId = "feature.shop", method = "setHidden" },
    ["shop.delete"] = { moduleId = "feature.shop", method = "deleteListing" },
    ["shop.purchase"] = { moduleId = "feature.shop", method = "purchase" },
    ["shop.lottery"] = { moduleId = "feature.shop", method = "lottery" },
    ["recycle.execute"] = { moduleId = "feature.recycle", method = "execute" },
    ["recycle.snapshot"] = { moduleId = "feature.recycle", method = "snapshot" },
    ["recycle.preference"] = { moduleId = "feature.recycle", method = "setPreference" },
    ["upgrades.summary"] = { moduleId = "feature.upgrades", method = "requestSummary" },
    ["upgrades.purchase"] = { moduleId = "feature.upgrades", method = "upgrade" },
    ["upgrades.refresh"] = { moduleId = "feature.upgrades", method = "refresh" },
    ["medical.execute"] = { moduleId = "feature.medical", method = "execute" },
    ["home.set"] = { moduleId = "feature.home", method = "setHome" },
    ["home.snapshot"] = { moduleId = "feature.home", method = "snapshot" },
    ["home.buyTemp"] = { moduleId = "feature.home", method = "buyTemp" },
    ["home.setTemp"] = { moduleId = "feature.home", method = "setTemp" },
    ["home.teleport"] = { moduleId = "feature.home", method = "teleportHome" },
    ["home.teleportTemp"] = { moduleId = "feature.home", method = "teleportTemp" },
    ["home.return"] = { moduleId = "feature.home", method = "returnToDeparture" },
    ["home.clearReturn"] = { moduleId = "feature.home", method = "clearReturn" },
    ["home.upgradeSafeZone"] = { moduleId = "feature.home", method = "upgradeSafeZone" },
    ["home.toggleSafeZone"] = { moduleId = "feature.home", method = "toggleSafeZone" },
    ["home.clearSafeZone"] = { moduleId = "feature.home", method = "clearSafeZone" },
    ["terminal.status"] = { moduleId = "feature.terminal", method = "requestStatus" },
    ["terminal.execute"] = { moduleId = "feature.terminal", method = "execute" },
    ["storage.status"] = { moduleId = "feature.storage", method = "requestStatus" },
    ["storage.networkState"] = { moduleId = "feature.storage", method = "requestNetworkState" },
    ["storage.organizerStatus"] = { moduleId = "feature.storage", method = "requestOrganizerStatus" },
    ["storage.execute"] = { moduleId = "feature.storage", method = "execute" },
    ["storage.index"] = { moduleId = "feature.storage", method = "startIndex" },
    ["storage.process"] = { moduleId = "feature.storage", method = "requestProcessJobs" },
    ["storage.snapshot"] = { moduleId = "feature.storage", method = "requestSnapshot" },
    ["storage.details"] = { moduleId = "feature.storage", method = "requestInstanceDetails" },
    ["autoloader.state"] = { moduleId = "feature.autoloader", method = "state" },
    ["autoloader.deposit"] = { moduleId = "feature.autoloader", method = "startDeposit" },
    ["autoloader.depositBatch"] = { moduleId = "feature.autoloader", method = "completeDepositBatch" },
    ["autoloader.cancel"] = { moduleId = "feature.autoloader", method = "cancelDeposit" },
    ["autoloader.withdraw"] = { moduleId = "feature.autoloader", method = "withdraw" },
    ["autoloader.fill"] = { moduleId = "feature.autoloader", method = "manualFill" },
    ["autoloader.reload"] = { moduleId = "feature.autoloader", method = "postReload" },
    ["companion.state"] = { moduleId = "feature.companion", method = "getState" },
    ["companion.purchase"] = { moduleId = "feature.companion", method = "purchase" },
    ["companion.sight"] = { moduleId = "feature.companion", method = "activateSight" },
    ["companion.combatMode"] = { moduleId = "feature.companion", method = "setCombatMode" },
    ["companion.followMode"] = { moduleId = "feature.companion", method = "setFollowMode" },
    ["companion.visible"] = { moduleId = "feature.companion", method = "toggleVisible" },
    ["companion.guardian"] = { moduleId = "feature.companion", method = "toggleGuardian" },
    ["companion.recall"] = { moduleId = "feature.companion", method = "recall" },
    ["attributes.perks"] = { moduleId = "feature.attributes", method = "requestListPerks" },
    ["attributes.quote"] = { moduleId = "feature.attributes", method = "requestAttributeQuote" },
    ["attributes.purchase"] = { moduleId = "feature.attributes", method = "purchaseAttribute" },
    ["attributes.traits"] = { moduleId = "feature.attributes", method = "requestListTraits" },
    ["attributes.traitQuote"] = { moduleId = "feature.attributes", method = "requestTraitQuote" },
    ["attributes.traitModify"] = { moduleId = "feature.attributes", method = "modifyTrait" },
    ["maintenance.execute"] = { moduleId = "feature.maintenance", method = "execute" },
    ["admin.snapshot"] = { moduleId = "feature.admin", method = "getSnapshot" },
    ["admin.save"] = { moduleId = "feature.admin", method = "setSettings" },
    ["admin.itemOverride"] = { moduleId = "feature.admin", method = "setItemOverride" },
    ["admin.clearItemOverride"] = { moduleId = "feature.admin", method = "clearItemOverride" },
}

return Protocol
